version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # nextjs:
  #   build: .
  #   restart: always
  #   image: node:18
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - NEXTAUTH_URL=${NEXTAUTH_URL}
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #     - GITHUB_ID=${GITHUB_ID}
  #     - GITHUB_SECRET=${GITHUB_SECRET}
  #     - PG_HOST=db
  #   working_dir: /app/app
  #   volumes:
  #     - .:/app/app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   command: bash -c "npx prisma generate && npm run dev"
