version: "3.1"
services:
  nextjs:
    env_file:
      - .env.docker
    image: node:18
    working_dir: /app/app
    volumes:
      - .:/app/app
    ports:
      - 3000:3000
    environment:
      - PG_HOST=db
    depends_on:
      - db
    command: bash -c "npx prisma generate && npm run dev"
