module.exports = {
  semi: false,
  singleQuote: true,
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  trailingComma: "es5",
  bracketSpacing: true,
  quoteProps: "as-needed",
  jsxSingleQuote: true,
  jsxBracketSameLine: true,
  arrowParens: "always",
  proseWrap: "preserve",
  htmlWhitespaceSensitivity: "ignore",
  vueIndentScriptAndStyle: false,
  endOfLine: "lf",
  embeddedLanguageFormatting: "auto",
  plugins: ["prettier-plugin-tailwindcss"],
};
